# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  luacov-reporter-lcov = {
    pname = "luacov-reporter-lcov";
    version = "4d881ddb4eeec5ac0cd7d4b7679e3e59f9ac5745";
    src = fetchFromGitHub {
      owner = "daurnimator";
      repo = "luacov-reporter-lcov";
      rev = "4d881ddb4eeec5ac0cd7d4b7679e3e59f9ac5745";
      fetchSubmodules = false;
      sha256 = "sha256-o+9E+pMVpWpd4M0gBnU0g9OA7UZjNbuqFa6WG2j73nE=";
    };
    date = "2019-11-01";
  };
}
